Traceback (most recent call last):
  File "/Users/lisabroadhead/Desktop/python-coding-dojo/flask_mysql/fullstack_four/server.py", line 1, in <module>
    from flask import Flask, render_template,redirect,require  # Import Flask to allow us to create our app
ImportError: cannot import name 'require' from 'flask' (/Users/lisabroadhead/.local/share/virtualenvs/fullstack_four-5WsKPNws/lib/python3.10/site-packages/flask/__init__.py)


Traceback (most recent call last):
  File "/Users/lisabroadhead/Desktop/python-coding-dojo/flask_mysql/fullstack_four/server.py", line 1, in <module>
    from flask import Flask, render_template,redirect,require  # Import Flask to allow us to create our app
ImportError: cannot import name 'require' from 'flask' (/Users/lisabroadhead/.local/share/virtualenvs/fullstack_four-5WsKPNws/lib/python3.10/site-packages/flask/__init__.py)

Traceback (most recent call last):
  File "/Users/lisabroadhead/Desktop/python-coding-dojo/flask_mysql/fullstack_six/server.py", line 3, in <module>
    from user import Users
  File "/Users/lisabroadhead/Desktop/python-coding-dojo/flask_mysql/fullstack_six/user.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/lisabroadhead/Desktop/python-coding-dojo/flask_mysql/fullstack_six/mysqlconnection.py", line 19
    query = cursor.mogrify(query, data)
    ^
IndentationError: expected an indented block after 'try' statement on line 18

